language: go
sudo: false
dist: trusty
git:
  depth: false
go:
  - tip
os:
  - linux

install:
  - go get github.com/gohugoio/hugo
  - go get --tags extended  github.com/gohugoio/hugo
script:
  - ./deploy.sh
